import { ToolConfig, AuditToolConfig, Feature, Step } from "@/constants/types";

export const NAV_ITEMS: { href: string; label: string }[] = [
  { href: "/", label: "Home" },
  { href: "/audit", label: "AI Spend" },
  { href: "/features", label: "Features" },
  { href: "/how-it-works", label: "How It Works" },
  { href: "/testimonials", label: "Testimonials" },
  { href: "/faq", label: "FAQ" },
];

export const FEATURES: Feature[] = [
  {
    icon: "◈",
    title: "AI Spend Analysis",
    description:
      "Break down your AI tooling costs by vendor, plan, and seat count.",
  },
  {
    icon: "↓",
    title: "Cost Optimization",
    description:
      "Get specific plan-level recommendations backed by current pricing data.",
  },
  {
    icon: "⊹",
    title: "Personalized AI Summary",
    description:
      "Receive an executive-ready summary of your stack's efficiency.",
  },
  {
    icon: "⇪",
    title: "Shareable Audit Reports",
    description:
      "Export and share results with finance or leadership in one click.",
  },
  {
    icon: "◫",
    title: "Team Spending Insights",
    description: "See per-seat cost and identify where spend is concentrated.",
  },
  {
    icon: "⌖",
    title: "Smart Savings Detection",
    description:
      "Surface hidden savings from plan mismatches and unused tiers.",
  },
];

export const STEPS: Step[] = [
  {
    number: "01",
    title: "Add Your AI Tools",
    description:
      "Enter the AI tools your team uses, the plan, and number of seats.",
  },
  {
    number: "02",
    title: "Generate Audit",
    description:
      "Our engine evaluates your stack against current pricing and team fit.",
  },
  {
    number: "03",
    title: "Save Money",
    description:
      "Act on clear recommendations and capture your savings immediately.",
  },
];

export const severityConfig: Record<
  string,
  { label: string; dot: string; border: string }
> = {
  high: {
    label: "High",
    dot: "bg-red-400",
    border: "border-red-500/40",
  },
  moderate: {
    label: "Moderate",
    dot: "bg-yellow-400",
    border: "border-yellow-500/40",
  },
  low: {
    label: "Low",
    dot: "bg-blue-400",
    border: "border-blue-500/60",
  },
  ok: {
    label: "Optimized",
    dot: "bg-emerald-400",
    border: "border-white/30",
  },
};

export const actionLabel: Record<string, string> = {
  "downgrade-plan": "Downgrade Plan",
  "switch-tool": "Switch Tool",
  "switch-to-api": "Consider API Billing",
  "reduce-seats": "Reduce Seats",
  optimized: "No Action Needed",
};

export const TOOL_CONFIG: Record<string, ToolConfig> = {
  Cursor: {
    plans: [
      { label: "Hobby", price: 0, note: "Free" },
      { label: "Pro", price: 20 },
      { label: "Pro+", price: 60 },
      { label: "Ultra", price: 200 },
      { label: "Teams", price: 40, note: "/seat" },
      { label: "Enterprise", price: 0, note: "Custom" },
    ],
  },

  "GitHub Copilot": {
    plans: [
      { label: "Free", price: 0 },
      { label: "Pro", price: 10 },
      { label: "Pro+", price: 39 },
      { label: "Business", price: 19, note: "/seat" },
      { label: "Enterprise", price: 39, note: "/seat" },
    ],
  },

  Claude: {
    plans: [
      { label: "Free", price: 0 },
      { label: "Pro", price: 20 },
      { label: "Max 5×", price: 100 },
      { label: "Max 20×", price: 200 },
      { label: "Team Standard", price: 25, note: "/seat" },
      { label: "Team Premium", price: 100, note: "/seat" },
      { label: "Enterprise", price: 0, note: "Custom" },
    ],
  },

  ChatGPT: {
    plans: [
      { label: "Free", price: 0 },
      { label: "Plus", price: 20 },
      { label: "Pro $100", price: 100 },
      { label: "Pro $200", price: 200 },
      { label: "Business", price: 25, note: "/seat" },
      { label: "Enterprise", price: 0, note: "Custom" },
    ],
  },

  "Anthropic API": {
    plans: [{ label: "Usage-based", price: 0, note: "Pay per token" }],
  },

  "OpenAI API": {
    plans: [{ label: "Usage-based", price: 0, note: "Pay per token" }],
  },

  Gemini: {
    plans: [
      { label: "Free", price: 0 },
      { label: "AI Pro", price: 19.99 },
      { label: "AI Ultra", price: 249.99 },
    ],
  },

  Windsurf: {
    plans: [
      { label: "Free", price: 0 },
      { label: "Pro", price: 20 },
      { label: "Max", price: 200 },
      { label: "Teams", price: 40, note: "/seat" },
      { label: "Enterprise", price: 0, note: "Custom" },
    ],
  },
};

export const TOOL_NAMES = Object.keys(TOOL_CONFIG);

export const AUDIT_TOOL_CONFIG: Record<string, AuditToolConfig> = {
  Cursor: {
    plans: {
      Hobby: {
        monthlyPrice: 0,
        recommendedMinSeats: 1,
        recommendedMaxSeats: 1,
        recommendedUseCases: ["coding", "learning", "side-projects"],
        idealTeamTypes: ["solo"],
        enterpriseFocused: false,
        collaborationFocused: false,
        apiAvailable: false,
        creditEligible: false,
        cheaperInternalAlternative: null,
        alternativeTools: [],
        reasoningNotes: [
          "Suitable for individual developers exploring AI-assisted coding.",
          "Usage limits make this plan unsuitable for production or team workflows.",
        ],
      },
      Pro: {
        monthlyPrice: 20,
        recommendedMinSeats: 1,
        recommendedMaxSeats: 4,
        recommendedUseCases: ["coding", "data-analysis"],
        idealTeamTypes: ["solo", "small-team"],
        enterpriseFocused: false,
        collaborationFocused: false,
        apiAvailable: false,
        creditEligible: false,
        cheaperInternalAlternative: "Hobby",
        alternativeTools: ["GitHub Copilot Pro", "Windsurf Pro"],
        reasoningNotes: [
          "Strong value for individual engineers and small teams up to ~4 seats.",
          "Provides frontier model access at a competitive per-seat price point.",
          "Beyond 4 seats, Teams pricing may offer better administrative controls.",
        ],
      },
      "Pro+": {
        monthlyPrice: 60,
        recommendedMinSeats: 1,
        recommendedMaxSeats: 3,
        recommendedUseCases: ["coding", "data-analysis"],
        idealTeamTypes: ["solo", "small-team"],
        enterpriseFocused: false,
        collaborationFocused: false,
        apiAvailable: false,
        creditEligible: false,
        cheaperInternalAlternative: "Pro",
        alternativeTools: ["GitHub Copilot Pro+", "Windsurf Pro"],
        reasoningNotes: [
          "3x usage headroom over Pro — warranted only for heavy daily coding workflows.",
          "At $60/seat, cost-benefit should be reviewed against actual usage consumption.",
          "Teams with moderate usage may find Cursor Pro sufficient at one-third the cost.",
        ],
      },
      Ultra: {
        monthlyPrice: 200,
        recommendedMinSeats: 1,
        recommendedMaxSeats: 2,
        recommendedUseCases: ["coding"],
        idealTeamTypes: ["solo"],
        enterpriseFocused: false,
        collaborationFocused: false,
        apiAvailable: false,
        creditEligible: false,
        cheaperInternalAlternative: "Pro+",
        alternativeTools: ["GitHub Copilot Enterprise", "Windsurf Max"],
        reasoningNotes: [
          "Designed for power users with extremely high daily coding throughput.",
          "At $200/seat/month, this plan requires clear evidence of usage saturation at Pro+ before it can be financially justified.",
          "Most engineering teams will not exhaust Pro+ limits; recommend usage audit before approving Ultra seats.",
        ],
      },
      Teams: {
        monthlyPrice: 40,
        recommendedMinSeats: 3,
        recommendedMaxSeats: 50,
        recommendedUseCases: ["coding", "data-analysis"],
        idealTeamTypes: ["small-team", "mid-team"],
        enterpriseFocused: false,
        collaborationFocused: true,
        apiAvailable: false,
        creditEligible: false,
        cheaperInternalAlternative: "Pro",
        alternativeTools: ["GitHub Copilot Business", "Windsurf Teams"],
        reasoningNotes: [
          "Adds SSO, RBAC, and centralized billing over the Pro plan.",
          "Economically justified once team size exceeds 3 seats and admin controls are needed.",
          "For 1–2 seat teams, individual Pro plans deliver equivalent functionality at half the cost.",
        ],
      },
      Enterprise: {
        monthlyPrice: 0, // custom
        recommendedMinSeats: 50,
        recommendedMaxSeats: 9999,
        recommendedUseCases: ["coding", "data-analysis"],
        idealTeamTypes: ["enterprise"],
        enterpriseFocused: true,
        collaborationFocused: true,
        apiAvailable: false,
        creditEligible: false,
        cheaperInternalAlternative: "Teams",
        alternativeTools: ["GitHub Copilot Enterprise"],
        reasoningNotes: [
          "Appropriate for large organizations requiring pooled usage, invoice billing, and SCIM provisioning.",
          "Custom pricing — validate commercial terms against headcount and compliance requirements.",
        ],
      },
    },
  },

  "GitHub Copilot": {
    plans: {
      Free: {
        monthlyPrice: 0,
        recommendedMinSeats: 1,
        recommendedMaxSeats: 1,
        recommendedUseCases: ["coding"],
        idealTeamTypes: ["solo"],
        enterpriseFocused: false,
        collaborationFocused: false,
        apiAvailable: false,
        creditEligible: false,
        cheaperInternalAlternative: null,
        alternativeTools: [],
        reasoningNotes: [
          "2,000 completions/month is sufficient for light or exploratory coding use.",
          "Not suitable for production engineering workflows.",
        ],
      },
      Pro: {
        monthlyPrice: 10,
        recommendedMinSeats: 1,
        recommendedMaxSeats: 4,
        recommendedUseCases: ["coding"],
        idealTeamTypes: ["solo", "small-team"],
        enterpriseFocused: false,
        collaborationFocused: false,
        apiAvailable: false,
        creditEligible: false,
        cheaperInternalAlternative: "Free",
        alternativeTools: ["Cursor Pro", "Windsurf Pro"],
        reasoningNotes: [
          "Lowest-cost paid option for AI coding assistance — strong value for individual developers.",
          "Unlimited completions at $10/seat is competitive against alternatives.",
        ],
      },
      "Pro+": {
        monthlyPrice: 39,
        recommendedMinSeats: 1,
        recommendedMaxSeats: 3,
        recommendedUseCases: ["coding"],
        idealTeamTypes: ["solo", "small-team"],
        enterpriseFocused: false,
        collaborationFocused: false,
        apiAvailable: false,
        creditEligible: false,
        cheaperInternalAlternative: "Pro",
        alternativeTools: ["Cursor Pro", "Windsurf Pro"],
        reasoningNotes: [
          "Provides 1,500 premium model requests vs 300 on Pro.",
          "Cost-justified only for engineers who regularly exhaust Pro-tier request limits.",
          "At nearly 4x the Pro price, usage patterns should be reviewed before upgrading.",
        ],
      },
      Business: {
        monthlyPrice: 19,
        recommendedMinSeats: 5,
        recommendedMaxSeats: 100,
        recommendedUseCases: ["coding"],
        idealTeamTypes: ["small-team", "mid-team"],
        enterpriseFocused: false,
        collaborationFocused: true,
        apiAvailable: false,
        creditEligible: false,
        cheaperInternalAlternative: "Pro",
        alternativeTools: ["Cursor Teams", "Windsurf Teams"],
        reasoningNotes: [
          "Adds IP indemnity, org-level policy controls, and audit logs over the Pro plan.",
          "Appropriate for teams where legal/compliance sign-off on AI tooling is required.",
          "For teams of 1–4 without compliance needs, individual Pro seats at $10 are more cost-effective.",
        ],
      },
      Enterprise: {
        monthlyPrice: 39,
        recommendedMinSeats: 50,
        recommendedMaxSeats: 9999,
        recommendedUseCases: ["coding"],
        idealTeamTypes: ["enterprise"],
        enterpriseFocused: true,
        collaborationFocused: true,
        apiAvailable: false,
        creditEligible: false,
        cheaperInternalAlternative: "Business",
        alternativeTools: ["Cursor Enterprise"],
        reasoningNotes: [
          "Adds fine-tuned model support and GitHub.com-integrated chat over Business.",
          "At $39/seat, the premium over Business ($19/seat) requires clear use of enterprise-exclusive features to justify.",
          "Organizations not leveraging fine-tuning or GitHub Enterprise integration should evaluate Business tier first.",
        ],
      },
    },
  },

  Claude: {
    plans: {
      Free: {
        monthlyPrice: 0,
        recommendedMinSeats: 1,
        recommendedMaxSeats: 1,
        recommendedUseCases: [
          "writing",
          "research",
          "coding",
          "customer-support",
        ],
        idealTeamTypes: ["solo"],
        enterpriseFocused: false,
        collaborationFocused: false,
        apiAvailable: false,
        creditEligible: false,
        cheaperInternalAlternative: null,
        alternativeTools: [],
        reasoningNotes: [
          "Suitable for light or exploratory use with daily message limits.",
          "Not appropriate for consistent professional or team workflows.",
        ],
      },
      Pro: {
        monthlyPrice: 20,
        recommendedMinSeats: 1,
        recommendedMaxSeats: 3,
        recommendedUseCases: [
          "writing",
          "research",
          "coding",
          "data-analysis",
          "customer-support",
        ],
        idealTeamTypes: ["solo", "small-team"],
        enterpriseFocused: false,
        collaborationFocused: false,
        apiAvailable: false,
        creditEligible: true,
        cheaperInternalAlternative: "Free",
        alternativeTools: ["ChatGPT Plus", "Gemini AI Pro"],
        reasoningNotes: [
          "5x message volume over Free at $20/month — strong value for individual professional use.",
          "Well suited to writing, analysis, and coding workflows for 1–3 users.",
          "Teams requiring shared workspaces or collaboration should evaluate Team Standard.",
        ],
      },
      "Max 5×": {
        monthlyPrice: 100,
        recommendedMinSeats: 1,
        recommendedMaxSeats: 2,
        recommendedUseCases: ["writing", "research", "coding", "data-analysis"],
        idealTeamTypes: ["solo", "small-team"],
        enterpriseFocused: false,
        collaborationFocused: false,
        apiAvailable: false,
        creditEligible: true,
        cheaperInternalAlternative: "Pro",
        alternativeTools: ["ChatGPT Pro $100", "Anthropic API"],
        reasoningNotes: [
          "5x the message volume of Pro — financially justified only when Pro limits are consistently exhausted.",
          "At $100/month, users should verify usage logs before committing to this tier.",
          "Heavy API-style workloads may be better served by Anthropic API direct with usage-based billing.",
        ],
      },
      "Max 20×": {
        monthlyPrice: 200,
        recommendedMinSeats: 1,
        recommendedMaxSeats: 1,
        recommendedUseCases: ["coding", "data-analysis", "research"],
        idealTeamTypes: ["solo"],
        enterpriseFocused: false,
        collaborationFocused: false,
        apiAvailable: false,
        creditEligible: true,
        cheaperInternalAlternative: "Max 5×",
        alternativeTools: ["Anthropic API"],
        reasoningNotes: [
          "20x Pro message volume — intended for power users with extremely high throughput needs.",
          "At $200/seat/month, this plan requires documented evidence of Max 5x saturation to justify.",
          "High-volume programmatic workloads should be redirected to Anthropic API for cost-variable billing.",
        ],
      },
      "Team Standard": {
        monthlyPrice: 25,
        recommendedMinSeats: 3,
        recommendedMaxSeats: 50,
        recommendedUseCases: [
          "writing",
          "research",
          "customer-support",
          "marketing",
        ],
        idealTeamTypes: ["small-team", "mid-team"],
        enterpriseFocused: false,
        collaborationFocused: true,
        apiAvailable: false,
        creditEligible: false,
        cheaperInternalAlternative: "Pro",
        alternativeTools: ["ChatGPT Business"],
        reasoningNotes: [
          "Adds shared workspaces and centralized billing at $25/seat — marginal premium over individual Pro.",
          "Cost-effective for teams of 3+ where collaboration and shared context are actively used.",
          "For solo users or pairs without collaboration needs, individual Pro at $20 is the better choice.",
        ],
      },
      "Team Premium": {
        monthlyPrice: 100,
        recommendedMinSeats: 3,
        recommendedMaxSeats: 50,
        recommendedUseCases: ["coding", "data-analysis"],
        idealTeamTypes: ["small-team", "mid-team"],
        enterpriseFocused: false,
        collaborationFocused: true,
        apiAvailable: false,
        creditEligible: false,
        cheaperInternalAlternative: "Team Standard",
        alternativeTools: ["ChatGPT Business", "GitHub Copilot Business"],
        reasoningNotes: [
          "Includes Claude Code — financially justified only for engineering teams actively using agentic coding workflows.",
          "At $100/seat/month, teams not using Claude Code should downgrade to Team Standard at $25/seat.",
          "Potential savings of $75/seat/month for teams not utilizing the premium feature set.",
        ],
      },
      Enterprise: {
        monthlyPrice: 0,
        recommendedMinSeats: 50,
        recommendedMaxSeats: 9999,
        recommendedUseCases: [
          "writing",
          "research",
          "coding",
          "data-analysis",
          "customer-support",
        ],
        idealTeamTypes: ["enterprise"],
        enterpriseFocused: true,
        collaborationFocused: true,
        apiAvailable: false,
        creditEligible: false,
        cheaperInternalAlternative: "Team Standard",
        alternativeTools: ["ChatGPT Enterprise"],
        reasoningNotes: [
          "Provides 500K context window, HIPAA compliance, SCIM provisioning, and SSO.",
          "Appropriate for regulated industries or organizations with data governance requirements.",
          "Custom pricing — validate against headcount, compliance needs, and context window requirements.",
        ],
      },
    },
  },

  ChatGPT: {
    plans: {
      Plus: {
        monthlyPrice: 20,
        recommendedMinSeats: 1,
        recommendedMaxSeats: 3,
        recommendedUseCases: [
          "writing",
          "research",
          "marketing",
          "customer-support",
        ],
        idealTeamTypes: ["solo", "small-team"],
        enterpriseFocused: false,
        collaborationFocused: false,
        apiAvailable: true,
        creditEligible: true,
        cheaperInternalAlternative: null,
        alternativeTools: ["Claude Pro", "Gemini AI Pro"],
        reasoningNotes: [
          "Competitive entry-level paid plan at $20/month for individual users.",
          "Includes GPT-5.5, Deep Research, Sora, and Codex — strong feature breadth.",
          "Teams sharing a single Plus account should consider Business for proper seat management.",
        ],
      },
      "Pro $100": {
        monthlyPrice: 100,
        recommendedMinSeats: 1,
        recommendedMaxSeats: 2,
        recommendedUseCases: ["research", "coding", "data-analysis"],
        idealTeamTypes: ["solo"],
        enterpriseFocused: false,
        collaborationFocused: false,
        apiAvailable: true,
        creditEligible: true,
        cheaperInternalAlternative: "Plus",
        alternativeTools: ["Claude Max 5×", "OpenAI API"],
        reasoningNotes: [
          "5x Plus usage capacity — appropriate only when Plus message limits are consistently reached.",
          "At $100/month for a single seat, usage patterns should be reviewed against Plus limits before upgrading.",
        ],
      },
      "Pro $200": {
        monthlyPrice: 200,
        recommendedMinSeats: 1,
        recommendedMaxSeats: 1,
        recommendedUseCases: ["research", "coding", "data-analysis"],
        idealTeamTypes: ["solo"],
        enterpriseFocused: false,
        collaborationFocused: false,
        apiAvailable: true,
        creditEligible: true,
        cheaperInternalAlternative: "Pro $100",
        alternativeTools: ["OpenAI API", "Anthropic API"],
        reasoningNotes: [
          "1M token context and 20x Plus usage — intended for extreme power-user scenarios.",
          "At $200/seat/month, programmatic or bulk workloads are almost always cheaper via OpenAI API direct.",
          "Recommend usage audit against API cost modeling before renewing this tier.",
        ],
      },
      Business: {
        monthlyPrice: 25,
        recommendedMinSeats: 3,
        recommendedMaxSeats: 100,
        recommendedUseCases: [
          "writing",
          "research",
          "marketing",
          "customer-support",
        ],
        idealTeamTypes: ["small-team", "mid-team"],
        enterpriseFocused: false,
        collaborationFocused: true,
        apiAvailable: true,
        creditEligible: false,
        cheaperInternalAlternative: "Plus",
        alternativeTools: ["Claude Team Standard"],
        reasoningNotes: [
          "Adds team workspace and data privacy guarantees over Plus at $25/seat.",
          "Strong choice for teams of 3+ where data-not-for-training is a compliance requirement.",
          "For 1–2 user teams without compliance requirements, Plus at $20 is equivalent in functionality.",
        ],
      },
      Enterprise: {
        monthlyPrice: 0,
        recommendedMinSeats: 50,
        recommendedMaxSeats: 9999,
        recommendedUseCases: [
          "writing",
          "research",
          "coding",
          "customer-support",
        ],
        idealTeamTypes: ["enterprise"],
        enterpriseFocused: true,
        collaborationFocused: true,
        apiAvailable: true,
        creditEligible: false,
        cheaperInternalAlternative: "Business",
        alternativeTools: ["Claude Enterprise"],
        reasoningNotes: [
          "Appropriate for large organizations requiring SSO, analytics, and unlimited GPT-5.5 access.",
          "Custom pricing — validate commercial terms against actual headcount and governance requirements.",
        ],
      },
    },
  },

  "Anthropic API": {
    plans: {
      "Usage-based": {
        monthlyPrice: 0,
        recommendedMinSeats: 1,
        recommendedMaxSeats: 9999,
        recommendedUseCases: [
          "coding",
          "data-analysis",
          "research",
          "customer-support",
        ],
        idealTeamTypes: ["solo", "small-team", "mid-team", "enterprise"],
        enterpriseFocused: false,
        collaborationFocused: false,
        apiAvailable: true,
        creditEligible: true,
        cheaperInternalAlternative: null,
        alternativeTools: ["OpenAI API"],
        reasoningNotes: [
          "Pay-per-token billing is cost-efficient for variable or bursty usage patterns.",
          "For consistent high-volume usage, model cost should be projected monthly and compared against flat-rate plans.",
          "Provides access to the full Claude model family with no seat restrictions.",
        ],
      },
    },
  },

  "OpenAI API": {
    plans: {
      "Usage-based": {
        monthlyPrice: 0,
        recommendedMinSeats: 1,
        recommendedMaxSeats: 9999,
        recommendedUseCases: [
          "coding",
          "data-analysis",
          "research",
          "customer-support",
        ],
        idealTeamTypes: ["solo", "small-team", "mid-team", "enterprise"],
        enterpriseFocused: false,
        collaborationFocused: false,
        apiAvailable: true,
        creditEligible: true,
        cheaperInternalAlternative: null,
        alternativeTools: ["Anthropic API"],
        reasoningNotes: [
          "Usage-based billing with access to GPT-5.4 family — appropriate for programmatic workloads.",
          "No fixed seat cost; expenses scale directly with consumption.",
          "Teams running predictable high-volume workloads should model monthly API spend against ChatGPT Business pricing.",
        ],
      },
    },
  },

  Gemini: {
    plans: {
      Free: {
        monthlyPrice: 0,
        recommendedMinSeats: 1,
        recommendedMaxSeats: 1,
        recommendedUseCases: ["writing", "research"],
        idealTeamTypes: ["solo"],
        enterpriseFocused: false,
        collaborationFocused: false,
        apiAvailable: false,
        creditEligible: false,
        cheaperInternalAlternative: null,
        alternativeTools: [],
        reasoningNotes: [
          "Adequate for light personal use with Gemini 2.5 Flash access.",
          "Not recommended for professional or team workflows.",
        ],
      },
      "AI Pro": {
        monthlyPrice: 19.99,
        recommendedMinSeats: 1,
        recommendedMaxSeats: 3,
        recommendedUseCases: [
          "writing",
          "research",
          "data-analysis",
          "marketing",
        ],
        idealTeamTypes: ["solo", "small-team"],
        enterpriseFocused: false,
        collaborationFocused: false,
        apiAvailable: true,
        creditEligible: true,
        cheaperInternalAlternative: "Free",
        alternativeTools: ["Claude Pro", "ChatGPT Plus"],
        reasoningNotes: [
          "Competitive at ~$20/month with access to Gemini 2.5/3 Pro and Deep Research.",
          "1,000 AI credits included — usage should be monitored to avoid credit exhaustion.",
          "For Google Workspace-embedded teams, this plan offers native productivity integration benefits.",
        ],
      },
      "AI Ultra": {
        monthlyPrice: 249.99,
        recommendedMinSeats: 1,
        recommendedMaxSeats: 1,
        recommendedUseCases: ["research", "data-analysis", "coding"],
        idealTeamTypes: ["solo"],
        enterpriseFocused: false,
        collaborationFocused: false,
        apiAvailable: true,
        creditEligible: true,
        cheaperInternalAlternative: "AI Pro",
        alternativeTools: ["Claude Max 20×", "ChatGPT Pro $200", "OpenAI API"],
        reasoningNotes: [
          "At $249.99/month, this is among the highest-priced single-seat AI plans currently available.",
          "25,000 AI credits and Veo 3.1 access — justified only for users with heavy video generation or research workloads.",
          "Most professional users will find AI Pro sufficient; upgrade requires documented saturation of Pro-tier credits.",
        ],
      },
    },
  },

  Windsurf: {
    plans: {
      Free: {
        monthlyPrice: 0,
        recommendedMinSeats: 1,
        recommendedMaxSeats: 1,
        recommendedUseCases: ["coding"],
        idealTeamTypes: ["solo"],
        enterpriseFocused: false,
        collaborationFocused: false,
        apiAvailable: false,
        creditEligible: false,
        cheaperInternalAlternative: null,
        alternativeTools: [],
        reasoningNotes: [
          "Unlimited tab completions on the free tier — suitable for light coding use.",
          "Premium model access is restricted; not recommended for production engineering workflows.",
        ],
      },
      Pro: {
        monthlyPrice: 20,
        recommendedMinSeats: 1,
        recommendedMaxSeats: 4,
        recommendedUseCases: ["coding", "data-analysis"],
        idealTeamTypes: ["solo", "small-team"],
        enterpriseFocused: false,
        collaborationFocused: false,
        apiAvailable: false,
        creditEligible: false,
        cheaperInternalAlternative: "Free",
        alternativeTools: ["Cursor Pro", "GitHub Copilot Pro"],
        reasoningNotes: [
          "Standard quota with full premium model access — competitive with Cursor Pro at the same price point.",
          "Good alternative for developers who prefer Windsurf's workflow over Cursor.",
        ],
      },
      Max: {
        monthlyPrice: 200,
        recommendedMinSeats: 1,
        recommendedMaxSeats: 2,
        recommendedUseCases: ["coding"],
        idealTeamTypes: ["solo"],
        enterpriseFocused: false,
        collaborationFocused: false,
        apiAvailable: false,
        creditEligible: false,
        cheaperInternalAlternative: "Pro",
        alternativeTools: ["Cursor Ultra", "GitHub Copilot Enterprise"],
        reasoningNotes: [
          "Heavy quota tier for power users — mirrors Cursor Ultra in price and positioning.",
          "At $200/seat/month, requires clear evidence of Pro quota exhaustion to justify the spend.",
        ],
      },
      Teams: {
        monthlyPrice: 40,
        recommendedMinSeats: 3,
        recommendedMaxSeats: 50,
        recommendedUseCases: ["coding", "data-analysis"],
        idealTeamTypes: ["small-team", "mid-team"],
        enterpriseFocused: false,
        collaborationFocused: true,
        apiAvailable: false,
        creditEligible: false,
        cheaperInternalAlternative: "Pro",
        alternativeTools: ["Cursor Teams", "GitHub Copilot Business"],
        reasoningNotes: [
          "Adds admin dashboard and centralized billing over Pro at $40/seat.",
          "Economically justified for teams of 3+ requiring centralized usage management.",
          "Smaller teams without admin requirements should use individual Pro plans.",
        ],
      },
      Enterprise: {
        monthlyPrice: 0,
        recommendedMinSeats: 50,
        recommendedMaxSeats: 9999,
        recommendedUseCases: ["coding"],
        idealTeamTypes: ["enterprise"],
        enterpriseFocused: true,
        collaborationFocused: true,
        apiAvailable: false,
        creditEligible: false,
        cheaperInternalAlternative: "Teams",
        alternativeTools: ["Cursor Enterprise", "GitHub Copilot Enterprise"],
        reasoningNotes: [
          "Custom pricing with RBAC, SSO, and hybrid deployment options.",
          "Appropriate for large engineering organizations with security and governance mandates.",
        ],
      },
    },
  },
};
