import { NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { auditResults } = body;

    const prompt = `
You are an AI financial audit assistant.

Generate a concise professional summary in under 100 words.

Focus on:
- overspending
- unnecessary plans
- optimization opportunities
- overall stack efficiency
- major savings opportunities

Keep the tone executive-friendly and financially credible.

Audit Results:
${JSON.stringify(auditResults)}
`;

    const apiKey = process.env.GEMINI_API_KEY?.trim();

    if (!apiKey) {
      throw new Error("GEMINI_API_KEY is missing from environment variables.");
    }

    // Official Google SDK initialize karna
    const genAI = new GoogleGenerativeAI(apiKey);

    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

    const result = await model.generateContent(prompt);
    const summary = result.response.text();

    if (!summary) {
      throw new Error("No summary generated by the model");
    }

    return NextResponse.json({
      success: true,
      summary,
    });
  } catch (error: unknown) {
    console.error("AI Summary Error:", error);

    const errorMessage =
      error instanceof Error ? error.message : "Failed to generate summary";

    return NextResponse.json(
      {
        success: false,
        message: errorMessage,
      },
      {
        status: 500,
      },
    );
  }
}
